name: Docker Image CI

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

  pull_request:
    branches: [ main ]
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y_%m_%d_%H_%M')"
    
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        tags: devopsteamsdb/devopsteamsdb:selenium_powershell_${{ steps.date.outputs.date }}
        file: Dockerfile
    
    - name: Login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Push image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: devopsteamsdb/devopsteamsdb:selenium_powershell_${{ steps.date.outputs.date }}
        file: Dockerfile
        
    - name: Push image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: devopsteamsdb/devopsteamsdb:selenium_powershell_latest
        file: Dockerfile

    - name: docker save image
      run: docker save devopsteamsdb/devopsteamsdb:selenium_powershell_${{ steps.date.outputs.date }} | gzip > selenium_powershell_${{ steps.date.outputs.date }}.gz
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: selenium_powershell_${{ steps.date.outputs.date }}
        release_name: Release selenium_powershell_${{ steps.date.outputs.date }}
        body: |
          Jenkins Version: ${{ env.JENKINS_VERSION }}
          This will overiid by next step
      
    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        file: "*.gz"
        release_id: ${{ steps.create_release.outputs.id }}
        overwrite: true
        verbose: true
        
        
